name: videos349 # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.3.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: A video editor # 79 char long summary
description: |
  An opinionated video editor.


grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: amd64

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: go
    source: .
    build-snaps:
      - go
    build-packages:
      - build-essential
      - gcc
      - libgl1-mesa-dev
      - xorg-dev
      - libc6-dev
    override-build: |
      set -xe
      cp $SNAPCRAFT_PART_SRC/ffmpeg/ffmpeg $SNAPCRAFT_PART_INSTALL/bin/ffmpeg
      cp $SNAPCRAFT_PART_SRC/ffmpeg/ffprobe $SNAPCRAFT_PART_INSTALL/bin/ffprobe
      cd $SNAPCRAFT_PART_SRC/linux
      go mod download
      go build -o $SNAPCRAFT_PART_INSTALL/bin/videos349 .
      go build -o $SNAPCRAFT_PART_INSTALL/bin/hasten ./hasten

  pickers:
    # See 'snapcraft plugins'
    plugin: go
    source: https://github.com/saenuma/pickers.git
    build-snaps:
      - go
    build-packages:
      - build-essential
      - gcc
      - libgl1-mesa-dev
      - xorg-dev
      - libc6-dev
    override-build: |
      set -xe
      go mod download
      go build -o $SNAPCRAFT_PART_INSTALL/bin/fpicker ./fpicker


apps: 
  videos349:
    command: bin/videos349
    extensions: [gnome]
  
  hasten:
    command: bin/hasten
    